# Generated by Django 3.2.7 on 2021-09-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
