# Generated by Django 3.2.7 on 2021-09-04 08:26

from django.db import migrations


def seed_profile(apps, schema_editor):
    Profile = apps.get_model('game_data', 'Profile')
    for item in Profile.objects.all():
        item.address_line_1 = '8888 University Drive'
        item.city = 'Burnaby'
        item.country = 'CA'
        item.mailcode = 'V5A1S6'
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0003_auto_20210904_0116'),
    ]

    operations = [
        migrations.RunPython(seed_profile)
    ]
